## 0) Importación librerías necesarias

In [4]:
# Importación de librerías necesarias
import pandas as pd
import numpy as np

# Verificación de versiones instaladas
print(f"¡Pandas importado! La versión de Pandas es: {pd.__version__}")
print(f"¡NumPy importado! La versión de NumPy es: {np.__version__}")

¡Pandas importado! La versión de Pandas es: 2.2.2
¡NumPy importado! La versión de NumPy es: 1.26.4

## 1) Carga y exploración de datos

In [15]:
#Importa un dataset en formato CSV en un DataFrame.
df_ventas = pd.read_csv('datos_ventas.csv')

#Inspecciona los datos con .head(), .info() y .describe().
print("El DataFrame Datos Ventas ha sido cargado exitosamente.")
print("\nDatos ventas\n")
print(f"{df_ventas.head()}\n")
print("\nInformación importante del DataFrame\n")
print(f"{df_ventas.info()}\n")
print("\nEstadística básica\n")
print(f"{df_ventas.describe()}\n")

#Identifica valores nulos y duplicados.
print(f"\nCantidad de nulos por columna")
print(df_ventas.isnull().sum())
print(f"\nCantidad de nulos por fila")
print(df_ventas.isnull().sum(axis=1))

duplicados = df_ventas.duplicated().sum()
print(f"\nEn el DataFrame hay {duplicados} datos duplicados")

El DataFrame Datos Ventas ha sido cargado exitosamente.

Datos ventas

   ID   Producto   Categoría  Precio  Cantidad      Ciudad Fecha_Venta
0   1     Laptop  Tecnología   800.0       5.0    Santiago  2025-01-01
1   2      Mouse  Accesorios    25.0      20.0  Valparaíso  2025-01-02
2   3    Teclado  Accesorios    45.0      10.0  Concepción  2025-01-03
3   4    Monitor  Tecnología   200.0       7.0   La Serena  2025-01-04
4   5  Impresora     Oficina   150.0       4.0    Rancagua  2025-01-05


Información importante del DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           24 non-null     int64
 1   Producto     23 non-null     object
 2   Categoría    22 non-null     object
 3   Precio       22 non-null     float64
 4   Cantidad     22 non-null     float64
 5   Ciudad       23 non-null     object
 6   Fecha_Venta  22 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.4+ KB
None


Estadística básica

              ID      Precio   Cantidad
count  24.000000   22.000000  22.000000
mean   11.541667  300.000000   9.272727
std     7.002976  259.013697   4.692261
min     1.000000   25.000000   4.000000
25%     5.750000   93.750000   6.000000
50%    11.500000  200.000000   8.000000
75%    17.250000  475.000000  11.500000
max    23.000000  800.000000  20.000000


Cantidad de nulos por columna
ID             0
Producto       1
Categoría      2
Precio         2
Cantidad       2
Ciudad         1
Fecha_Venta    2
dtype: int64

Cantidad de nulos por fila
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    1
19    0
20    4
21    3
22    2
23    0
dtype: int64

En el DataFrame hay 1 datos duplicados

## 2) Limpieza y transformación de datos

In [14]:
df_ventas

    ID    Producto   Categoría  Precio  Cantidad       Ciudad Fecha_Venta
0    1      Laptop  Tecnología   800.0       5.0     Santiago  2025-01-01
1    2       Mouse  Accesorios    25.0      20.0   Valparaíso  2025-01-02
2    3     Teclado  Accesorios    45.0      10.0   Concepción  2025-01-03
3    4     Monitor  Tecnología   200.0       7.0    La Serena  2025-01-04
4    5   Impresora     Oficina   150.0       4.0     Rancagua  2025-01-05
5    6      Tablet  Tecnología   300.0       9.0     Santiago  2025-01-06
6    7     Celular  Tecnología   500.0      15.0  Antofagasta  2025-01-07
7    8   Audífonos  Accesorios    75.0      12.0     Valdivia  2025-01-08
8    9      Cámara  Fotografía   400.0       6.0      Iquique  2025-01-09
9   10  Smartwatch  Accesorios   180.0       8.0       Temuco  2025-01-10
10  11      Laptop  Tecnología   800.0       5.0     Santiago  2025-01-11
11  12       Mouse  Accesorios    25.0      20.0   Valparaíso  2025-01-12
12  13     Teclado  Accesorios    45.0      10.0   Concepción  2025-01-13
13  14     Monitor  Tecnología   200.0       7.0    La Serena  2025-01-14
14  15   Impresora     Oficina   150.0       4.0     Rancagua  2025-01-15
15  16      Tablet  Tecnología   300.0       9.0     Santiago  2025-01-16
16  17     Celular  Tecnología   500.0      15.0  Antofagasta  2025-01-17
17  18   Audífonos  Accesorios    75.0      12.0     Valdivia  2025-01-18
18  19      Cámara  Fotografía     NaN       6.0      Iquique  2025-01-19
19  20  Smartwatch  Accesorios   180.0       8.0       Temuco  2025-01-20
20  21      Tablet         NaN   250.0       NaN          NaN         NaN
21  22         NaN  Tecnología   600.0       NaN  Antofagasta         NaN
22  23      Laptop         NaN     NaN       7.0     Santiago  2025-01-24
23   1      Laptop  Tecnología   800.0       5.0     Santiago  2025-01-01

In [ ]:
#Imputa valores nulos utilizando estrategias adecuadas (media,mediana o moda).
#Borrar filas con dos o mas nulos
df_ventas = df_ventas.dropna(thresh = df.shape[1] - 1)

#Elimina registros duplicados.
#Convierte columnas categóricas en variables numéricas si es necesario.